owner: amblerapp
repo: status-rss

sites:
  - name: RSSBox
    url: https://rssbox.ambler.app/
  - name: RSSBox (Render)
    url: $RSSBOX_RENDER
  - name: RSSHub
    url: https://rsshub.ambler.app/
  - name: RSSHub (Render)
    url: $RSSHUB_RENDER
  - name: RSS-Bridge
    url: https://rssbridge.ambler.app/
  - name: RSS-Bridge (Render)
    url: $RSSBRIDGE_RENDER
  - name: Reddit-RSS
    url: https://reddit-rss.ambler.app/
  - name: Reddit-RSS (Render)
    url: $REDDITRSS_RENDER

status-website:
  cname: rss.status.ambler.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RSS Feed Generator Status | Ambler App
  introTitle: "**Upptime** for RSS Feed Generator"
  introMessage: RSS 피드제작기 모니터
